const BUDGET_DATA = {
    "t2": { options: [{ name: "Aporte Sugerido (Familia)", isFamilyPrice: true, priceAdult: 50 }] },
    "t4": { options: [{ name: "Entrada Cultural", priceAdult: 16 }] },
    "t6": { defaultUnchecked: true, options: [{ name: "Aporte Sugerido (Familia)", isFamilyPrice: true, priceAdult: 50 }] },
    "t7": { options: [{ name: "Visita Guiada Cubiertas", priceAdult: 10 }] },
    "t8": { options: [{ name: "Entrada General", priceAdult: 18 }] },
    "t9": { defaultUnchecked: true, options: [{ name: "Aporte Sugerido (Familia)", isFamilyPrice: true, priceAdult: 50 }] },
    "t11": { options: [{ name: "Ascensor Mirador", priceAdult: 4.50 }, { name: "Parque de Atracciones", priceAdult: 39 }] },
    "t12": { options: [{ name: "Boleto Sencillo (Metro/Bus)", priceAdult: 2.50 }] },
    "t13": { defaultUnchecked: true, options: [{ name: "Visita Diurna", priceAdult: 25 }, { name: "Visita Nocturna", priceAdult: 39 }] },
    "t15": { options: [{ name: "Visita Autoguiada", priceAdult: 16 }] },
    "t18": { options: [{ name: "Ascensor Exterior", priceAdult: 1 }] },
    "t19": { options: [{ name: "Bus 150", priceAdult: 2.50 }, { name: "Teleférico de Montjuïc (Ida y Vuelta)", priceAdult: 16 }] },
    "t_poble": { options: [{ name: "Entrada General Grupo", isFamilyPrice: true, priceAdult: 56.40 }] },
    "t25": { options: [{ name: "Aporte Sugerido (Familia)", isFamilyPrice: true, priceAdult: 50 }] },
    "t27": { options: [{ name: "Aeri del Port (Ida)", priceAdult: 12.50 }, { name: "Aeri del Port (Ida y Vuelta)", priceAdult: 20 }] },
    "t28": { options: [{ name: "Boleto Sencillo (Metro/Bus)", priceAdult: 2.50 }] },
    "t29": { options: [{ name: "Ya Reservado (18:00hs)", isFamilyPrice: true, priceAdult: 117 }] },
    "t30": { options: [{ name: "Entrada General", priceAdult: 21 }] },
    "t32": { options: [{ name: "Ya Reservado (09:30hs)", isFamilyPrice: true, priceAdult: 154.5 }] },
    "t33": { options: [{ name: "Acceso Gratuito", priceAdult: 0, price14: 0, price11: 0, price8: 0 }] },
    "t34": { options: [{ name: "Ya Reservado (15:45hs)", isFamilyPrice: true, priceAdult: 118 }] },
    "t36": { options: [{ name: "Mirador Básico", priceAdult: 18 }] }
};
