const HOSPEDAJES = [];

const PUNTOS_TURISTICOS = [
  // DIA 1 (28/9) - Lunes
  {
    "id": "m1",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Llegada a Madrid y Check-in",
    "lat": 40.4168,
    "lng": -3.7038,
    "tiempo": "10:08 - 12:30",
    "descripcion": "Llegada en tren de Valencia a la estación de Madrid (10:08). Traslado al hospedaje para realizar el check-in o dejar el equipaje y refrescarse antes de almorzar.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Madrid+Atocha+Estacion",
    "viability": { "horario": "Tren Ouigo/AVE", "tarifas": "Traslado" },
    "viability_full": "Logística: Tren Valencia -> Madrid (salida 08:12, llegada 10:08). Traslado al alojamiento para el check-in."
  },
  {
    "id": "m2",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Almuerzo en Mercado de San Miguel",
    "lat": 40.4155,
    "lng": -3.7090,
    "tiempo": "13:00 - 14:30",
    "descripcion": "Mercado gastronómico histórico cubierto. Un excelente lugar para un primer picoteo de tapas premium, postres y café en el centro histórico.",
    "imagen": "https://images.unsplash.com/photo-1543158266-00669f4ad616?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Mercado+de+San+Miguel+Madrid",
    "viability": { "horario": "10:00 - 00:00", "tarifas": "Entrada libre" },
    "viability_full": "Mercado de San Miguel: Abre de domingo a jueves de 10:00 a 00:00 (viernes y sábados hasta las 01:00). Ideal para un almuerzo de tapas y picoteo relajado."
  },
  {
    "id": "m3",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Plaza Mayor",
    "lat": 40.4154,
    "lng": -3.7074,
    "tiempo": "14:30 - 15:30",
    "descripcion": "La emblemática plaza porticada de Madrid. Una gran oportunidad para ver su arquitectura del Madrid de los Austrias y tomar fotos.",
    "imagen": "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Plaza+Mayor+Madrid",
    "viability": { "horario": "Abierto 24h", "tarifas": "Gratuito" },
    "viability_full": "Plaza Mayor: Acceso público libre y gratuito. Punto histórico neurálgico del centro de Madrid."
  },
  {
    "id": "m4",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Puerta del Sol",
    "lat": 40.4169,
    "lng": -3.7038,
    "tiempo": "15:30 - 17:00",
    "descripcion": "Plaza central de Madrid. Aquí podrás ver la estatua del Oso y el Madroño, el Kilómetro Cero y pasear por las calles comerciales adyacentes.",
    "imagen": "https://images.unsplash.com/photo-1509840841025-9088ba78a826?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Puerta+del+Sol+Madrid",
    "viability": { "horario": "Abierto 24h", "tarifas": "Gratuito" },
    "viability_full": "Puerta del Sol: Zona peatonal comercial muy concurrida. Punto cero de las carreteras españolas."
  },
  {
    "id": "m5",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Encuentro y Preparación",
    "lat": 40.4190,
    "lng": -3.7025,
    "tiempo": "17:00 - 18:30",
    "descripcion": "Tiempo libre en los alrededores de la calle Montera para descansar, tomar un café o pasear antes de iniciar el tour guiado.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Calle+Montera+32+Madrid",
    "viability": { "horario": "Llegar 18:15", "tarifas": "Punto encuentro" },
    "viability_full": "Civitatis Montera: Ubicado en Calle de la Montera, 32. Presentarse a las 18:15 para validar la reserva del free tour."
  },
  {
    "id": "m6",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Free Tour Madrid Civitatis",
    "lat": 40.4190,
    "lng": -3.7025,
    "tiempo": "18:30 - 20:30",
    "descripcion": "Tour a pie guiado de orientación por los sitios clave de Madrid: Sol, Plaza Mayor, Palacio Real (exterior) y finalización en Plaza de Oriente. Perfecto como toma de contacto inicial.",
    "imagen": "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800",
    "isFreeTour": true,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Plaza+de+Oriente+Madrid",
    "viability": { "horario": "18:30 - 20:30", "tarifas": "Propina libre" },
    "viability_full": "Free Tour: Duración 2 horas. Comienza en Calle Montera 32 y finaliza en la Plaza de Oriente. Reserva de cupo online obligatoria (máx 6 personas por reserva, vuestro grupo familiar de 5 entra sin problema)."
  },
  {
    "id": "m7",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Cena en zona Ópera / Plaza de Oriente",
    "lat": 40.4180,
    "lng": -3.7115,
    "tiempo": "20:30 en adelante",
    "descripcion": "Cena relajada en las inmediaciones del final del tour. Recomendación: no ir al Templo de Debod este día ya que el atardecer es a las 20:01 y no llegaréis a tiempo con luz.",
    "imagen": "https://images.unsplash.com/photo-1543158266-00669f4ad616?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Restaurantes+Opera+Madrid",
    "viability": { "horario": "Cena libre", "tarifas": "Según consumo" },
    "viability_full": "Nota: Se evita trasladar al Templo de Debod hoy por superposición horaria y atardecer a las 20:01."
  },

  // DIA 2 (29/9) - Martes
  {
    "id": "m12",
    "dia": 2,
    "fecha": "29/9",
    "nombre": "Museo Nacional del Prado",
    "lat": 40.4138,
    "lng": -3.6921,
    "tiempo": "10:00 - 12:00",
    "descripcion": "Una de las pinacotecas más célebres del mundo. Recorrido familiar enfocado en las obras maestras absolutas: Las Meninas de Velázquez, El Jardín de las Delicias del Bosco y Las Pinturas Negras de Goya.",
    "imagen": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Museo+del+Prado+Madrid",
    "viability": { "horario": "10:00 - 20:00", "tarifas": "€15 (Menores gratis)" },
    "viability_full": "Museo del Prado: Lunes a sábado de 10:00 a 20:00. Entrada general: €15. Menores de 18 años entran gratis (acreditación requerida). Es indispensable reservar el pase horario online con antelación para evitar largas colas."
  },
  {
    "id": "m13",
    "dia": 2,
    "fecha": "29/9",
    "nombre": "Paseo por Plaza de Cibeles y Puerta de Alcalá",
    "lat": 40.4190,
    "lng": -3.6887,
    "tiempo": "12:15 - 13:00",
    "descripcion": "Recorrido fotográfico de camino al restaurante. Podrás contemplar la Fuente de Cibeles, el Palacio de Comunicaciones (Ayuntamiento) y la monumental Puerta de Alcalá.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Puerta+de+Alcala+Madrid",
    "viability": { "horario": "Exterior", "tarifas": "Gratuito" },
    "viability_full": "Puntos de interés: Monumento y fuente al aire libre. Opcional: mirador del Palacio de Cibeles (€4 general, €2 de 7-14 años, requiere reserva online)."
  },
  {
    "id": "m14",
    "dia": 2,
    "fecha": "29/9",
    "nombre": "Almuerzo en la zona del Retiro",
    "lat": 40.4190,
    "lng": -3.6820,
    "tiempo": "13:00 - 14:15",
    "descripcion": "Disfruta de la variada gastronomía de tabernas tradicionales o bistrós modernos que se encuentran en las calles adyacentes al Parque del Retiro.",
    "imagen": "https://images.unsplash.com/photo-1543158266-00669f4ad616?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Restaurantes+cerca+del+Retiro+Madrid",
    "viability": { "horario": "Almuerzo", "tarifas": "Libre" },
    "viability_full": "Recomendación: Elegir un lugar cercano a la entrada norte del parque para optimizar los tiempos."
  },
  {
    "id": "m10",
    "dia": 2,
    "fecha": "29/9",
    "nombre": "Paseo por Gran Vía (España/Callao a Alcalá)",
    "lat": 40.4196,
    "lng": -3.7051,
    "tiempo": "14:30 - 18:15",
    "descripcion": "Tarde dedicada a recorrer sin prisas la arteria más icónica de la capital. Famosa por sus cines, teatros, arquitectura monumental y grandes tiendas.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Gran+Via+Madrid",
    "viability": { "horario": "Paseo libre", "tarifas": "Gratuito" },
    "viability_full": "Gran Vía: Avenida monumental. El paseo a pie permite apreciar los imponentes edificios como el Metrópolis y hacer compras."
  },
  {
    "id": "m11",
    "dia": 2,
    "fecha": "29/9",
    "nombre": "Chocolate con Churros en San Ginés / Descanso",
    "lat": 40.4168,
    "lng": -3.7071,
    "tiempo": "19:00 - 20:15",
    "descripcion": "Un merecido descanso en la chocolatería más famosa de España para disfrutar de sus clásicos churros con chocolate antes de volver al hotel.",
    "imagen": "https://images.unsplash.com/photo-1599388053648-9f37c442436d?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Chocolateria+San+Gines+Madrid",
    "viability": { "horario": "Abierto 24h", "tarifas": "Aprox €5-7" },
    "viability_full": "Chocolatería San Ginés: Abierta las 24 horas todos los días del año. Suele haber cola en horas pico, pero avanza rápido."
  },

  // DIA 3 (30/9) - Miércoles
  {
    "id": "m20",
    "dia": 3,
    "fecha": "30/9",
    "nombre": "Templo de Debod",
    "lat": 40.4241,
    "lng": -3.7178,
    "tiempo": "10:00 - 11:00",
    "descripcion": "Templo egipcio original del siglo II a.C. donado a España. Visita matutina para recorrer el parque y el interior del templo.",
    "imagen": "https://images.unsplash.com/photo-1542382156909-9ae37b3f56fd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Templo+de+Debod+Madrid",
    "viability": { "horario": "10:00 - 20:00", "tarifas": "Gratuito" },
    "viability_full": "Templo de Debod: Cerrado los lunes. Abierto de martes a domingo de 10:00 a 20:00. La entrada al templo interior es libre y gratuita con aforo muy reducido. El parque exterior permanece abierto sin restricciones."
  },
  {
    "id": "m19",
    "dia": 3,
    "fecha": "30/9",
    "nombre": "Faro de Moncloa",
    "lat": 40.4354,
    "lng": -3.7214,
    "tiempo": "11:30 - 12:30",
    "descripcion": "Torre de iluminación y mirador de 92 metros de altura que ofrece espectaculares vistas panorámicas de 360 grados de Madrid y la sierra.",
    "imagen": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Faro+de+Moncloa+Madrid",
    "viability": { "horario": "09:30 - 20:00", "tarifas": "€4 (niños €2)" },
    "viability_full": "Faro de Moncloa: Cerrado los lunes. Abierto de martes a domingo. Entrada general: €4. Reducida (7-14 años): €2. La estancia máxima en el mirador es de 30 minutos. Puede cerrar sin previo aviso por vientos fuertes."
  },
  {
    "id": "m18",
    "dia": 3,
    "fecha": "30/9",
    "nombre": "Almuerzo por Malasaña",
    "lat": 40.4260,
    "lng": -3.7042,
    "tiempo": "13:00 - 14:30",
    "descripcion": "Almuerzo en el bohemio y vibrante barrio de Malasaña, lleno de opciones gastronómicas y ambiente moderno.",
    "imagen": "https://images.unsplash.com/photo-1543158266-00669f4ad616?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Restaurantes+Malasaña+Madrid",
    "viability": { "horario": "Almuerzo", "tarifas": "Libre" },
    "viability_full": "Malasaña ofrece una gran variedad de menús del día y restaurantes de todo tipo."
  },
  {
    "id": "m17",
    "dia": 3,
    "fecha": "30/9",
    "nombre": "Catedral de la Almudena",
    "lat": 40.4156,
    "lng": -3.7146,
    "tiempo": "15:00 - 16:00",
    "descripcion": "La catedral de Madrid, consagrada en 1993. Destaca por su colorido techo neogótico contemporáneo y por ubicarse justo enfrente del Palacio Real.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Catedral+de+la+Almudena+Madrid",
    "viability": { "horario": "10:00 - 20:30", "tarifas": "Donativo €1" },
    "viability_full": "Catedral de la Almudena: Abierta todos los días. Acceso a la catedral es por donativo (€1). Nota: El acceso al museo y subida a la cúpula tiene un coste de €8 general / €5 reducida."
  },
  {
    "id": "m16",
    "dia": 3,
    "fecha": "30/9",
    "nombre": "Palacio Real de Madrid (Visita Gratuita)",
    "lat": 40.4180,
    "lng": -3.7142,
    "tiempo": "16:30 - 19:00",
    "descripcion": "Visita al palacio real más grande de Europa Occidental. Fila de acceso a partir de las 16:30 hs para disfrutar de la visita gratuita (entre 17:00 a 19:00 hs).",
    "imagen": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Palacio+Real+de+Madrid",
    "viability": { "horario": "17:00 - 19:00 (Gratis)", "tarifas": "Gratuito" },
    "viability_full": "Palacio Real: Estar a las 16:30 en la fila para acceder al horario gratuito (de 17:00 a 19:00 de lunes a jueves para ciudadanos de la UE e iberoamericanos). Es indispensable llevar pasaporte para acreditar nacionalidad. Evitar bultos o mochilas grandes."
  },

  // DIA 4 (1/10) - Jueves
  {
    "id": "m8",
    "dia": 4,
    "fecha": "1/10",
    "nombre": "Tour Bernabéu (Classic)",
    "lat": 40.4531,
    "lng": -3.6883,
    "tiempo": "09:30 - 11:30",
    "descripcion": "Visita libre al renovado estadio Santiago Bernabéu. Podrás ver el museo con los trofeos, las vistas panorámicas del estadio y la tienda oficial.",
    "imagen": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Estadio+Santiago+Bernabeu+Madrid",
    "viability": { "horario": "09:00 - 19:00", "tarifas": "Desde €37" },
    "viability_full": "Tour Bernabéu: El estadio abre a las 09:00 de lunes a sábado. Compra online obligatoria de la entrada Classic (franja 09:30). Los días de partido o víspera puede haber restricciones en vestuarios y césped. Recorrido con tramos de escaleras."
  },
  {
    "id": "m9",
    "dia": 4,
    "fecha": "1/10",
    "nombre": "Paseo y Almuerzo en Barrio de Salamanca",
    "lat": 40.4292,
    "lng": -3.6841,
    "tiempo": "11:50 - 13:30",
    "descripcion": "Paseo por las amplias avenidas del distrito más exclusivo de Madrid, caracterizado por sus tiendas elegantes, bellas fachadas y excelentes restaurantes para almorzar.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Calle+Serrano+Madrid",
    "viability": { "horario": "Almuerzo", "tarifas": "Libre" },
    "viability_full": "Barrio de Salamanca: Zona residencial/comercial premium. Ofrece muchas opciones gastronómicas de primer nivel."
  },
  {
    "id": "m15",
    "dia": 4,
    "fecha": "1/10",
    "nombre": "Parque de El Retiro (Paseo a pie)",
    "lat": 40.4153,
    "lng": -3.6836,
    "tiempo": "14:30 - 18:00",
    "descripcion": "Tarde recorriendo el pulmón verde de Madrid. Contempla el espectacular Estanque Grande y el Palacio de Cristal desde su exterior (el interior está temporalmente cerrado por obras). Disfruta de la sombra y senderos históricos.",
    "imagen": "https://images.unsplash.com/photo-1558642084-fd07fae5282e?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Parque+del+Retiro+Madrid",
    "viability": { "horario": "06:00 - 22:00", "tarifas": "Gratuito" },
    "viability_full": "Parque del Retiro: Acceso gratuito. Nota: El Palacio de Cristal permanece cerrado temporalmente al público para reformas estructurales; se visita solo el entorno exterior. El paseo en barca fue expresamente excluido de la planificación, centrando la tarde en caminatas y recreación en los jardines."
  },
  {
    "id": "m24",
    "dia": 4,
    "fecha": "1/10",
    "nombre": "Museo de las Ilusiones",
    "lat": 40.4124,
    "lng": -3.7042,
    "tiempo": "18:15 - 19:30",
    "descripcion": "Una experiencia interactiva y divertida para toda la familia. Repleto de trucos visuales, cuartos inclinados, hologramas y desafíos ópticos ideales para sacar fotos creativas.",
    "imagen": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Museo+de+las+Ilusiones+Madrid",
    "viability": { "horario": "09:30 - 22:00", "tarifas": "Pack Familiar desde €48" },
    "viability_full": "Museo de las Ilusiones: Entrada combinada familiar (2 adultos + 2 niños): desde €48 online + 1 niño adicional (€12) = total aproximado €60. Reservar online para asegurar horario."
  },

  // DIA 5 (2/10) - Viernes
  {
    "id": "m21",
    "dia": 5,
    "fecha": "2/10",
    "nombre": "Museo Nacional Centro de Arte Reina Sofía",
    "lat": 40.4079,
    "lng": -3.6946,
    "tiempo": "10:00 - 12:00",
    "descripcion": "Museo de arte del siglo XX y contemporáneo. Visita imperdible para apreciar el Guernica de Pablo Picasso y obras de Salvador Dalí y Joan Miró.",
    "imagen": "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Museo+Reina+Sofia+Madrid",
    "viability": { "horario": "10:00 - 21:00", "tarifas": "€12 (Menores gratis)" },
    "viability_full": "Reina Sofía: Cerrado los martes. Abierto el viernes de 10:00 a 21:00. Entrada general: €12. Menores de 18 años entran gratis (solicitar ticket en taquilla con identificación). Horario de mayor afluencia familiar: 10:00 - 12:00."
  },
  {
    "id": "m22",
    "dia": 5,
    "fecha": "2/10",
    "nombre": "Almuerzo en Legazpi / Matadero",
    "lat": 40.3900,
    "lng": -3.6970,
    "tiempo": "12:30 - 14:00",
    "descripcion": "Desplazamiento al sur de la ciudad y almuerzo en restaurantes locales de la zona de Legazpi o dentro del área gastronómica de Matadero.",
    "imagen": "https://images.unsplash.com/photo-1543158266-00669f4ad616?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Matadero+Madrid+Restaurantes",
    "viability": { "horario": "Almuerzo", "tarifas": "Libre" },
    "viability_full": "Fácil acceso en metro (Línea 3 a Legazpi) o caminata desde el museo."
  },
  {
    "id": "m23",
    "dia": 5,
    "fecha": "2/10",
    "nombre": "Madrid Río y Matadero Madrid",
    "lat": 40.3922,
    "lng": -3.6974,
    "tiempo": "14:00 - 17:30",
    "descripcion": "Tarde de diversión al aire libre en Madrid Río, un gran parque lineal junto al río Manzanares que cuenta con 17 áreas de juegos infantiles espectaculares. El paseo incluye la visita al complejo cultural Matadero Madrid.",
    "imagen": "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Matadero+Madrid",
    "viability": { "horario": "09:00 - 22:00", "tarifas": "Acceso libre" },
    "viability_full": "Matadero Madrid: El recinto general abre todos los días de 09:00 a 22:00. Las salas de exposiciones abren por la tarde (martes a domingos). Acceso al complejo es libre y gratuito. Madrid Río tiene toboganes y tirolesas infantiles."
  },

  // DIA 6 (3/10) - Sábado
  {
    "id": "m25",
    "dia": 6,
    "fecha": "3/10",
    "nombre": "Compras de último momento por el Centro",
    "lat": 40.4172,
    "lng": -3.7045,
    "tiempo": "10:00 - 13:15",
    "descripcion": "Tiempo disponible para adquirir recuerdos y caminar por las peatonales comerciales como calle Arenal, Preciados o calle Mayor.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Calle+Preciados+Madrid",
    "viability": { "horario": "Compras", "tarifas": "Libre" },
    "viability_full": "Zona totalmente peatonal en el centro comercial de Madrid."
  },
  {
    "id": "m26",
    "dia": 6,
    "fecha": "3/10",
    "nombre": "Almuerzo de despedida y recogida de maletas",
    "lat": 40.4168,
    "lng": -3.7038,
    "tiempo": "13:30 - 15:00",
    "descripcion": "Último almuerzo en la ciudad y posterior recogida del equipaje. Finalización del itinerario a las 15:00 en punto para trasladarse a la estación de tren/aeropuerto con suficiente margen para el Tax Refund.",
    "imagen": "https://images.unsplash.com/photo-1543158266-00669f4ad616?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Puerta+del+Sol+Madrid",
    "viability": { "horario": "Cierre a las 15:00", "tarifas": "Vuelo de salida 20:00" },
    "viability_full": "Logística: A las 15:00 finaliza todo para recoger maletas y dirigirse al aeropuerto de Barajas con tiempo. Vuelo internacional sale a las 20:00. Necesario realizar trámites de devolución de impuestos (Tax Refund)."
  }
];
