const HOSPEDAJES = [
  {
    "opcion": "12",
    "hospedaje": "Sofisticado y renovado - 2BD 2BTH-Malasaña",
    "sitio": "Airbnb",
    "importe": "Reservado",
    "direccion": "Calle Andrés Borrego, 13 3, Madrid, Comunidad de Madrid 28004, España",
    "cancelacion": "Confirmado",
    "camas": "4 camas",
    "calificacion": "Airbnb",
    "link": "https://www.airbnb.com.ar/rooms/38011908",
    "lat": 40.42348,
    "lng": -3.70658,
    "dorm": "2",
    "banos": "2",
    "address_estimated": false
  }
];

const PUNTOS_TURISTICOS = [
  // DIA 1 (28/9) - Lunes
  {
    "id": "m1",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Llegada a Madrid y Check-in",
    "lat": 40.4168,
    "lng": -3.7038,
    "tiempo": "10:08 - 12:30",
    "descripcion": "Llegada en tren de Valencia a la estación de Madrid (10:08). Traslado al hospedaje para realizar el check-in o dejar el equipaje y refrescarse antes de almorzar.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Madrid+Atocha+Estacion",
    "viability": { "horario": "Tren Ouigo/AVE", "tarifas": "Traslado" },
    "viability_full": "Logística: Tren Valencia -> Madrid (salida 08:12, llegada 10:08). Traslado al alojamiento para el check-in."
  },
  {
    "id": "m2",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Almuerzo en la zona Centro",
    "lat": 40.4169,
    "lng": -3.7038,
    "tiempo": "12:45 - 14:30",
    "descripcion": "Almuerzo familiar en un restaurante del centro o en los alrededores de la Plaza Mayor para recargar energías antes del tour.",
    "imagen": "https://images.unsplash.com/photo-1543158266-00669f4ad616?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Restaurantes+Plaza+Mayor+Madrid",
    "viability": { "horario": "Almuerzo libre", "tarifas": "Según consumo" },
    "viability_full": "Almuerzo previo al tour. Almorzar temprano para llegar con margen al punto de encuentro del free tour en Plaza Mayor."
  },
  {
    "id": "m3",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Free Tour Madrid SANDEMANs",
    "lat": 40.4154,
    "lng": -3.7074,
    "tiempo": "15:00 - 17:30",
    "descripcion": "Tour a pie de 2h 30m para una gran introducción a la historia de Madrid. Pasa por Plaza Mayor, Puerta del Sol, Palacio Real (exterior), Catedral de la Almudena y Teatro Real.",
    "imagen": "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800",
    "isFreeTour": true,
    "isReserved": true,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Plaza+Mayor+Madrid",
    "viability": { "horario": "Llegar 14:45", "tarifas": "Propina libre" },
    "viability_full": "Free Tour SANDEMANs: Duración 2.5 horas. Comienza a las 15:00 en la Plaza Mayor (frente a la Oficina de Turismo) y finaliza en la Plaza de Isabel II (Ópera). Es recomendable reservar online con antelación."
  },
  {
    "id": "m4",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Merienda en Mercado de San Miguel y Plaza Mayor",
    "lat": 40.4155,
    "lng": -3.7090,
    "tiempo": "17:45 - 19:00",
    "descripcion": "Al terminar el tour en la plaza de Ópera, caminata breve al Mercado de San Miguel para disfrutar de un primer picoteo de tapas, café o postres con calma en este mercado histórico cubierto.",
    "imagen": "https://images.unsplash.com/photo-1543158266-00669f4ad616?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Mercado+de+San+Miguel+Madrid",
    "viability": { "horario": "10:00 - 00:00", "tarifas": "Entrada libre" },
    "viability_full": "Mercado de San Miguel: Abre de domingo a jueves de 10:00 a 00:00. Ideal para picotear algo y luego dar un paseo tranquilo por la Plaza Mayor."
  },
  {
    "id": "m5",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Paseo por Puerta del Sol",
    "lat": 40.4169,
    "lng": -3.7038,
    "tiempo": "19:00 - 20:00",
    "descripcion": "Paseo peatonal por la plaza central de Madrid. Excelente momento para tomarse fotos con la estatua del Oso y el Madroño, el cartel de Tío Pepe y pisar el Kilómetro Cero.",
    "imagen": "https://images.unsplash.com/photo-1509840841025-9088ba78a826?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Puerta+del+Sol+Madrid",
    "viability": { "horario": "Abierto 24h", "tarifas": "Gratuito" },
    "viability_full": "Puerta del Sol: Zona peatonal comercial muy concurrida en el centro. Ideal para recorrerla a pie al atardecer."
  },
  {
    "id": "m6",
    "dia": 1,
    "fecha": "28/9",
    "nombre": "Cena en zona Centro / Ópera",
    "lat": 40.4180,
    "lng": -3.7115,
    "tiempo": "20:00 en adelante",
    "descripcion": "Cena familiar en la zona centro cerca del alojamiento para terminar el día de llegada de forma relajada.",
    "imagen": "https://images.unsplash.com/photo-1543158266-00669f4ad616?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Restaurantes+Opera+Madrid",
    "viability": { "horario": "Cena libre", "tarifas": "Según consumo" },
    "viability_full": "Nota: Se evita trasladar al Templo de Debod hoy por superposición horaria y atardecer a las 20:01. Queda pospuesto para el miércoles."
  },

  // DIA 2 (29/9) - Martes
  {
    "id": "m13",
    "dia": 2,
    "fecha": "29/9",
    "nombre": "Paseo por Plaza de Cibeles y Puerta de Alcalá",
    "lat": 40.4190,
    "lng": -3.6887,
    "tiempo": "10:00 - 11:00",
    "descripcion": "Paseo matutino previo al museo. Recorrido fotográfico para contemplar la Fuente de Cibeles, el Palacio de Cibeles (Ayuntamiento) y la monumental Puerta de Alcalá antes de descender hacia el Prado.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Puerta+de+Alcala+Madrid",
    "viability": { "horario": "Exterior (10:00 - 11:00)", "tarifas": "Gratuito" },
    "viability_full": "Puntos de interés: Monumento y fuente al aire libre. Paseo fotográfico ideal a las 10:00 hs antes del ingreso de las 11:15 al Museo del Prado. Opcional: mirador del Palacio de Cibeles."
  },
  {
    "id": "m12",
    "dia": 2,
    "fecha": "29/9",
    "nombre": "Museo Nacional del Prado",
    "lat": 40.4138,
    "lng": -3.6921,
    "tiempo": "11:15 - 13:15",
    "descripcion": "Una de las pinacotecas más célebres del mundo. Recorrido familiar enfocado en las obras maestras absolutas: Las Meninas de Velázquez, El Jardín de las Delicias del Bosco y Las Pinturas Negras de Goya.",
    "imagen": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800",
    "isFreeTour": false,
    "isReserved": true,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Museo+del+Prado+Madrid",
    "viability": { "horario": "11:15 - 13:15 (Entrada reservada: 11:15 hs)", "tarifas": "✅ Entradas compradas (€30.00 total)" },
    "viability_full": "Museo del Prado:\n* Estado: ✅ Entradas ya compradas para las 11:15 hs.\n* Duración: 2 horas de visita (11:15 a 13:15 hs).\n* Costo Total: €30.00 (2 adultos €15 c/u + 3 menores gratis).\n* Acceso: Presentar entradas electrónicas en el acceso reservado para evitar colas de taquilla."
  },

  {
    "id": "m10",
    "dia": 2,
    "fecha": "29/9",
    "nombre": "Paseo por Gran Vía (España/Callao a Alcalá)",
    "lat": 40.4196,
    "lng": -3.7051,
    "tiempo": "14:30 - 18:15",
    "descripcion": "Tarde dedicada a recorrer sin prisas la arteria más icónica de la capital. Famosa por sus cines, teatros, arquitectura monumental y grandes tiendas.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Gran+Via+Madrid",
    "viability": { "horario": "Paseo libre", "tarifas": "Gratuito" },
    "viability_full": "Gran Vía: Avenida monumental. El paseo a pie permite apreciar los imponentes edificios como el Metrópolis y hacer compras."
  },
  {
    "id": "m11",
    "dia": 2,
    "fecha": "29/9",
    "nombre": "Chocolate con Churros en San Ginés / Descanso",
    "lat": 40.4168,
    "lng": -3.7071,
    "tiempo": "19:00 - 20:15",
    "descripcion": "Un merecido descanso en la chocolatería más famosa de España para disfrutar de sus clásicos churros con chocolate antes de volver al hotel.",
    "imagen": "https://images.unsplash.com/photo-1599388053648-9f37c442436d?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Chocolateria+San+Gines+Madrid",
    "viability": { "horario": "Abierto 24h", "tarifas": "Aprox €5-7" },
    "viability_full": "Chocolatería San Ginés: Abierta las 24 horas todos los días del año. Suele haber cola en horas pico, pero avanza rápido."
  },

  // DIA 3 (30/9) - Miércoles
  {
    "id": "m19",
    "dia": 3,
    "fecha": "30/9",
    "nombre": "Faro de Moncloa",
    "lat": 40.4354,
    "lng": -3.7214,
    "tiempo": "09:45 - 11:15",
    "descripcion": "Visita a primera hora al mirador de 92 metros de altura para disfrutar de espectaculares vistas panorámicas de 360 grados de Madrid y la sierra antes de descender hacia Debod.",
    "imagen": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Faro+de+Moncloa+Madrid",
    "viability": { "horario": "09:30 - 20:00", "tarifas": "€4 (niños €2)" },
    "viability_full": "Faro de Moncloa: Apertura a las 09:30 hs. Entrada general: €4. Reducida (7-14 años): €2. La estancia máxima en el mirador es de 30 minutos. Puede cerrar sin previo aviso por vientos fuertes."
  },
  {
    "id": "m20",
    "dia": 3,
    "fecha": "30/9",
    "nombre": "Templo de Debod",
    "lat": 40.4241,
    "lng": -3.7178,
    "tiempo": "12:00 - 13:00",
    "descripcion": "Templo egipcio original del siglo II a.C. donado a España. Visita al parque exterior y recorrido por el interior del templo con entrada reservada a las 12:00 hs.",
    "imagen": "https://images.unsplash.com/photo-1542382156909-9ae37b3f56fd?w=800",
    "isFreeTour": false,
    "isReserved": true,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Templo+de+Debod+Madrid",
    "viability": { "horario": "12:00 hs (Entrada reservada)", "tarifas": "✅ Entrada reservada (Gratuito)" },
    "viability_full": "Templo de Debod:\n* Estado: ✅ Entrada reservada para las 12:00 hs (visita de 12:00 a 13:00 hs).\n* Costo: Gratuito con pase reservado para el interior.\n* Regulación: Aforo reducido en el interior para conservación del monumento.\n* Entorno: Parque del Cuartel de la Montaña con vistas a la Casa de Campo y Palacio Real."
  },
  {
    "id": "m18",
    "dia": 3,
    "fecha": "30/9",
    "nombre": "Almuerzo por Malasaña / Centro",
    "lat": 40.4260,
    "lng": -3.7042,
    "tiempo": "13:15 - 14:45",
    "descripcion": "Almuerzo en el bohemio y vibrante barrio de Malasaña o zona Centro, lleno de opciones gastronómicas y ambiente moderno.",
    "imagen": "https://images.unsplash.com/photo-1543158266-00669f4ad616?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Restaurantes+Malasaña+Madrid",
    "viability": { "horario": "Almuerzo", "tarifas": "Libre" },
    "viability_full": "Malasaña ofrece una gran variedad de menús del día y restaurantes de todo tipo."
  },
  {
    "id": "m17",
    "dia": 3,
    "fecha": "30/9",
    "nombre": "Catedral de la Almudena",
    "lat": 40.4156,
    "lng": -3.7146,
    "tiempo": "15:00 - 16:00",
    "descripcion": "La catedral de Madrid, consagrada en 1993. Destaca por su colorido techo neogótico contemporáneo y por ubicarse justo enfrente del Palacio Real.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Catedral+de+la+Almudena+Madrid",
    "viability": { "horario": "10:00 - 20:30", "tarifas": "Donativo €1" },
    "viability_full": "Catedral de la Almudena: Abierta todos los días. Acceso a la catedral es por donativo (€1). Nota: El acceso al museo y subida a la cúpula tiene un coste de €8 general / €5 reducida."
  },
  {
    "id": "m16",
    "dia": 3,
    "fecha": "30/9",
    "nombre": "Palacio Real de Madrid (Visita Gratuita)",
    "lat": 40.4180,
    "lng": -3.7142,
    "tiempo": "16:30 - 19:00",
    "descripcion": "Visita al palacio real más grande de Europa Occidental. Fila de acceso a partir de las 16:30 hs para disfrutar de la visita gratuita (entre 17:00 a 19:00 hs).",
    "imagen": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Palacio+Real+de+Madrid",
    "viability": { "horario": "17:00 - 19:00 (Gratis)", "tarifas": "Gratuito" },
    "viability_full": "Palacio Real: Estar a las 16:30 en la fila para acceder al horario gratuito (de 17:00 a 19:00 de lunes a jueves para ciudadanos de la UE e iberoamericanos). Es indispensable llevar pasaporte para acreditar nacionalidad. Evitar bultos o mochilas grandes."
  },

  // DIA 4 (1/10) - Jueves
  {
    "id": "m8",
    "dia": 4,
    "fecha": "1/10",
    "nombre": "Tour Bernabéu (Classic)",
    "lat": 40.4531,
    "lng": -3.6883,
    "tiempo": "09:30 - 11:30",
    "descripcion": "Visita libre al renovado estadio Santiago Bernabéu. Podrás ver el museo con los trofeos, las vistas panorámicas del estadio y la tienda oficial.",
    "imagen": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Estadio+Santiago+Bernabeu+Madrid",
    "viability": { "horario": "09:00 - 19:00", "tarifas": "Desde €37" },
    "viability_full": "Tour Bernabéu: El estadio abre a las 09:00 de lunes a sábado. Compra online obligatoria de la entrada Classic (franja 09:30). Los días de partido o víspera puede haber restricciones en vestuarios y césped. Recorrido con tramos de escaleras."
  },
  {
    "id": "m9",
    "dia": 4,
    "fecha": "1/10",
    "nombre": "Paseo y Almuerzo en Barrio de Salamanca",
    "lat": 40.4292,
    "lng": -3.6841,
    "tiempo": "11:50 - 13:30",
    "descripcion": "Paseo por las amplias avenidas del distrito más exclusivo de Madrid, destacando la famosa calle Serrano con sus tiendas elegantes, bellas fachadas y restaurantes para almorzar.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Calle+Serrano+Madrid",
    "viability": { "horario": "Almuerzo", "tarifas": "Libre" },
    "viability_full": "Barrio de Salamanca: Zona residencial/comercial premium. Ideal caminar por la calle Serrano. Ofrece muchas opciones gastronómicas de primer nivel."
  },
  {
    "id": "m15",
    "dia": 4,
    "fecha": "1/10",
    "nombre": "Parque de El Retiro (Paseo a pie)",
    "lat": 40.4153,
    "lng": -3.6836,
    "tiempo": "14:30 - 18:00",
    "descripcion": "Tarde recorriendo el pulmón verde de Madrid. Contempla el espectacular Estanque Grande y el Palacio de Cristal desde su exterior (el interior está temporalmente cerrado por obras). Disfruta de la sombra y senderos históricos.",
    "imagen": "https://images.unsplash.com/photo-1558642084-fd07fae5282e?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Parque+del+Retiro+Madrid",
    "viability": { "horario": "06:00 - 22:00", "tarifas": "Gratuito" },
    "viability_full": "Parque del Retiro: Acceso gratuito. Nota: El Palacio de Cristal permanece cerrado temporalmente al público para reformas estructurales; se visita solo el entorno exterior. El paseo en barca fue expresamente excluido de la planificación, centrando la tarde en caminatas y recreación en los jardines."
  },
  {
    "id": "m24",
    "dia": 4,
    "fecha": "1/10",
    "nombre": "Museum of Senses (Museo de las Sensaciones)",
    "lat": 40.4184,
    "lng": -3.7013,
    "tiempo": "18:15 - 19:30",
    "descripcion": "Una experiencia interactiva que desafía tus percepciones y despierta la curiosidad. Con más de 30 exhibiciones interactivas como el túnel de vórtice, cama de clavos y laberinto de espejos. En este bloque, 1 adulto y 2 niños (11 y 8 años) visitan este museo.",
    "imagen": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Museum+of+Senses+Madrid",
    "viability": { "horario": "10:00 - 20:00", "tarifas": "1 Adulto + 2 Niños: desde €49" },
    "viability_full": "Museum of Senses: Ubicado en Calle de la Virgen de los Peligros, 5. Recorrido autoguiado de 1 a 1.5 horas. Se aconseja comprar online. Entrada para 1 adulto y 2 niños (11 y 8 años) = desde €49 online. Incluye medias (la experiencia es sin zapatos) y un kit de degustación dulce."
  },
  {
    "id": "m_legends",
    "dia": 4,
    "fecha": "1/10",
    "nombre": "Legends: The Home of Football (Museo del Fútbol)",
    "lat": 40.4166,
    "lng": -3.7030,
    "tiempo": "18:15 - 19:45",
    "descripcion": "Un espacio interactivo y de exhibición dedicado a la historia del fútbol mundial. Cuenta con reliquias históricas, camisetas originales usadas por leyendas y experiencias de realidad virtual. En este bloque, 2 adultos (1 adulto + hijo de 14 años) visitan este museo.",
    "imagen": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Legends+The+Home+of+Football+Madrid",
    "viability": { "horario": "10:00 - 20:30 (Último acceso 18:30)", "tarifas": "2 Adultos: desde €45.80" },
    "viability_full": "Legends: The Home of Football: Ubicado en Carrera de San Jerónimo, 2 (Puerta del Sol). Visita para 2 adultos (1 adulto + hijo de 14 años, quien abona entrada de adulto de 14+ años) a €22.90 cada uno = total €45.80. La última admisión es a las 18:30 y cierra a las 20:30."
  },
  {
    "id": "m_rey_leon",
    "dia": 4,
    "fecha": "1/10",
    "nombre": "Musical El Rey León",
    "lat": 40.4206,
    "lng": -3.7090,
    "tiempo": "20:00 - 23:00",
    "descripcion": "Obra de teatro musical espectacular en la Gran Vía.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Teatro+Lope+de+Vega+Madrid",
    "viability": { "horario": "20:00 hs", "tarifas": "€50 estimado" },
    "viability_full": "El Rey León (Teatro Lope de Vega): Entrada estimada €50 por persona para Ale y los niños (4 personas)."
  },

  // DIA 5 (2/10) - Viernes
  {
    "id": "m27",
    "dia": 5,
    "fecha": "2/10",
    "nombre": "Tren a Toledo (Ida y Vuelta)",
    "lat": 39.8628,
    "lng": -4.0273,
    "tiempo": "09:00 - 10:00",
    "descripcion": "Traslado en tren de alta velocidad (AVE/Avant) desde Atocha hacia la ciudad medieval de Toledo (viaje de 30 min).",
    "imagen": "https://images.unsplash.com/photo-1548678967-f1aca58f6236?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Toledo+Spain",
    "viability": { "horario": "Día completo", "tarifas": "Tren desde €13 a €22" },
    "viability_full": "Toledo: Accesible rápidamente en tren. Se recomienda comprar los billetes de tren ida y vuelta sin equipaje con antelación. Niños menores de 14 años suelen tener descuento del 40% en Renfe."
  },
  {
    "id": "m_toledo_tour",
    "dia": 5,
    "fecha": "2/10",
    "nombre": "Tour Civitatis Toledo",
    "lat": 39.8593,
    "lng": -4.0253,
    "tiempo": "11:00 - 13:30",
    "descripcion": "Recorrido de 2h30m guiado por la ciudad de Toledo.",
    "imagen": "https://images.unsplash.com/photo-1548678967-f1aca58f6236?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Plaza+de+Zocodover+Toledo",
    "viability": { "horario": "11:00 hs", "tarifas": "€48 total" },
    "viability_full": "Tour Civitatis en Toledo, costo total de €48 para toda la familia."
  },

  // DIA 6 (3/10) - Sábado
  {
    "id": "m21",
    "dia": 6,
    "fecha": "3/10",
    "nombre": "Museo Nacional Centro de Arte Reina Sofía",
    "lat": 40.4079,
    "lng": -3.6946,
    "tiempo": "10:00 - 12:00",
    "descripcion": "Museo de arte del siglo XX y contemporáneo. Visita imperdible para apreciar el Guernica de Pablo Picasso y obras de Salvador Dalí y Joan Miró.",
    "imagen": "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Museo+Reina+Sofia+Madrid",
    "viability": { "horario": "10:00 - 21:00", "tarifas": "€12 (Menores gratis)" },
    "viability_full": "Reina Sofía: Abierto los sábados de 10:00 a 21:00. Entrada general: €12. Menores de 18 años entran gratis (solicitar ticket en taquilla con identificación)."
  },
  {
    "id": "m25",
    "dia": 6,
    "fecha": "3/10",
    "nombre": "Compras de último momento por el Centro",
    "lat": 40.4172,
    "lng": -3.7045,
    "tiempo": "12:00 - 13:30",
    "descripcion": "Tiempo disponible para adquirir recuerdos y caminar por las peatonales comerciales como calle Arenal, Preciados o calle Mayor.",
    "imagen": "https://images.unsplash.com/photo-1549849171-09f62448c5dd?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Calle+Preciados+Madrid",
    "viability": { "horario": "Compras", "tarifas": "Libre" },
    "viability_full": "Zona totalmente peatonal en el centro comercial de Madrid."
  },
  {
    "id": "m26",
    "dia": 6,
    "fecha": "3/10",
    "nombre": "Almuerzo de despedida y recogida de maletas",
    "lat": 40.4168,
    "lng": -3.7038,
    "tiempo": "13:30 - 15:00",
    "descripcion": "Último almuerzo en la ciudad y posterior recogida del equipaje. Finalización del itinerario a las 15:00 en punto para trasladarse a la estación de tren/aeropuerto con suficiente margen para el Tax Refund.",
    "imagen": "https://images.unsplash.com/photo-1543158266-00669f4ad616?w=800",
    "isFreeTour": false,
    "maps_link": "https://www.google.com/maps/search/?api=1&query=Puerta+del+Sol+Madrid",
    "viability": { "horario": "Cierre a las 15:00", "tarifas": "Vuelo de salida 20:00" },
    "viability_full": "Logística: A las 15:00 finaliza todo para recoger maletas y dirigirse al aeropuerto de Barajas con tiempo. Vuelo internacional sale a las 20:00. Necesario realizar trámites de devolución de impuestos (Tax Refund)."
  }
];
